name: Lint and Build Docker

on:
  push:
    paths:
      - '**.py'
      - Dockerfile
  pull_request:
    paths:
      - '**.py'
      - Dockerfile

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install flake8
        run: |
          pip install flake8
      - name: Run flake8
        run: flake8 .

  docker-build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t wumpus-game .

      - name: Run Docker image to test it
        run: |
          docker run -i wumpus-game <<EOF
          1
          2
          EOF
